//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassAttendance()
        {
            this.Students = new HashSet<Student>();
        }

        public List<ClassAttendance> StudentList = new List<ClassAttendance>();
        public int AttendanceID { get; set; }
        public int SectionID { get; set; }
        public System.DateTime Date { get; set; }
        public string Semester { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public int CourseId { get; set; }
        public int statusid { get; set; }

        public virtual status status { get; set; }
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
