//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fe
    {
        public int FeeID { get; set; }
        public Nullable<int> ScholarshipID { get; set; }
        public int StudentID { get; set; }
        public int LookupID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public double NewFee { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual Scholarshipss Scholarshipss { get; set; }
        public virtual Student Student { get; set; }
    }
}
