//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeeId { get; set; }
        public int Fees { get; set; }
        public string Semester { get; set; }
        public System.DateTime Date { get; set; }
    }
}
