//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public int DepartmentID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Sectionss Sectionss { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
