//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int StudentID { get; set; }
        public int ResultID { get; set; }
        public Nullable<double> GPA { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Student Student { get; set; }
    }
}
