//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int CoursesID { get; set; }
        public System.DateTime Time { get; set; }
        public int SectionID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
